<#
.SYNOPSIS
    One-time guided setup for a new machine. Asks for the 6 values this
    whole project needs, exactly once each, then writes them to BOTH
    places that need them - the Docker .env file AND your PowerShell
    $PROFILE - so nothing needs typing twice.

.DESCRIPTION
    Two values (OpenObserve user/password) are needed by both Docker
    Compose (via .env) and claude-report.ps1 (via $env: variables) -
    those two systems never share config automatically, which is the
    real source of "why do I have to set this up twice" friction. This
    script exists specifically to remove that friction: answer once,
    both places get updated.

    Safe to re-run any time (e.g. rotating a token) - it replaces its
    own clearly-marked block in $PROFILE rather than duplicating lines
    on every run, and won't touch anything else you've added to your
    profile.

.PARAMETER EnvPath
    Where to write the .env file for docker-compose. Defaults to
    docker\.env, relative to wherever THIS script lives (the project
    root) - deliberately not just ".env" in the current directory, since
    depending on which folder you happen to be standing in when you run
    a script is exactly the kind of mistake that caused real, confusing
    Docker bind-mount failures earlier in this project. Run this script
    from the project root (the folder this file itself is in), or pass
    -EnvPath explicitly if your layout differs.

.EXAMPLE
    cd path\to\claude-history-ingestor    # the project root - docker-compose.yml is in .\docker\ underneath it
    .\setEnvironment.ps1
#>

param(
    [string]$EnvPath = "docker\.env"
)

Write-Host "=== One-time setup: 6 values, entered once, used everywhere ===`n"

# --- 1. Claude history source (Docker only) ---
$defaultHistoryPath = Join-Path $HOME ".claude\projects"
Write-Host "1. Claude Code history folder (Docker reads your local session files from here)"
$historySource = Read-Host "   Path [$defaultHistoryPath]"
if (-not $historySource) { $historySource = $defaultHistoryPath }
# docker-compose bind mounts need forward slashes even on Windows.
$historySource = $historySource -replace '\\', '/'

# --- 2 & 3. OpenObserve credentials (shared by Docker AND claude-report.ps1) ---
Write-Host "`n2. OpenObserve login - used by BOTH docker-compose AND claude-report.ps1"
$ooUser = Read-Host "   Username/email [user@gamma.co.uk]"
if (-not $ooUser) { $ooUser = "user@gamma.co.uk" }
$ooPasswordSecure = Read-Host "   Password" -AsSecureString
$ooPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($ooPasswordSecure))

# --- 4, 5, 6. JIRA credentials (claude-report.ps1 only) ---
Write-Host "`n3. JIRA - used by claude-report.ps1"
$jiraBase = Read-Host "   Base URL [https://gammatelecom.atlassian.net]"
if (-not $jiraBase) { $jiraBase = "https://gammatelecom.atlassian.net" }
$jiraUser = Read-Host "   Your JIRA email [user@gamma.co.uk]"
if (-not $jiraUser) { $jiraUser = "user@gamma.co.uk" }
$jiraTokenSecure = Read-Host "   API token (create at https://id.atlassian.com/manage-profile/security/api-tokens)" -AsSecureString
$jiraToken = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($jiraTokenSecure))

# --- Write .env for docker-compose ---
$envFolder = Split-Path $EnvPath -Parent
if ($envFolder -and -not (Test-Path $envFolder)) {
    Write-Host "`nCan't write to '$EnvPath' - the folder '$envFolder' doesn't exist here."
    Write-Host "Run this script from the project root (the folder containing this script AND the docker\ subfolder), or pass -EnvPath explicitly."
    return
}
$envContent = @"
CLAUDE_HISTORY_SOURCE=$historySource
OPENOBSERVE_USER=$ooUser
OPENOBSERVE_PASSWORD=$ooPassword
"@
Set-Content -Path $EnvPath -Value $envContent -NoNewline
Write-Host "`nWrote $EnvPath (for docker compose up)"

# --- Update $PROFILE with a clearly-marked, replaceable block ---
$beginMarker = "# ===== BEGIN claude-history-ingestor managed env vars (auto-generated by setEnvironment.ps1) ====="
$endMarker   = "# ===== END claude-history-ingestor managed env vars ====="
$block = @"
$beginMarker
`$env:OPENOBSERVE_USER = "$ooUser"
`$env:OPENOBSERVE_PASSWORD = "$ooPassword"
`$env:JIRA_BASE = "$jiraBase"
`$env:JIRA_USER = "$jiraUser"
`$env:JIRA_TOKEN = "$jiraToken"
$endMarker
"@

if (-not (Test-Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
}
$existing = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
if ($existing -and $existing.Contains($beginMarker)) {
    # Replace the existing managed block in place - re-running this
    # script (e.g. after rotating a token) updates it cleanly instead of
    # duplicating five more lines below the old ones.
    $pattern = [regex]::Escape($beginMarker) + "(.|\n)*?" + [regex]::Escape($endMarker)
    $updated = [regex]::Replace($existing, $pattern, $block)
    Set-Content -Path $PROFILE -Value $updated -NoNewline
} else {
    Add-Content -Path $PROFILE -Value "`n$block"
}
Write-Host "Updated $PROFILE (for claude-report.ps1 - and OpenObserve creds are shared with docker-compose too)"

Write-Host "`n=== Done ==="
Write-Host "Docker: cd to this folder, run 'docker compose up -d'"
Write-Host "PowerShell: close and reopen your terminal (profile changes need a fresh session), then just run:"
Write-Host "  .\claude-report.ps1 -Ticket `"YOUR-TICKET`""